### ISSUE TITLE
upgrade analyzer

### ISSUE THREAD

**Issue by a-eniou-pvotal** [tnc1997/dart-xml-serializable#10]
Hello,

Could you upgrade the `analyzer` to ^3.0.0 as it makes a conflict with Freezed Library

Thanks

**Comment by tnc1997** [comment]
Hi @a-eniou-pvotal, thank you for letting me know, I'll aim to release an update to the `xml_serializable` package today.

**Comment by a-eniou-pvotal** [comment]
@tnc1997 Thanks a lot

**Comment by a-eniou-pvotal** [comment]
@tnc1997 Your Pr has version 2.0.0, I made a new PR with version 3.0.0
https://github.com/tnc1997/dart-xml-serializable/pull/12

**Comment by tnc1997** [comment]
Hi @a-eniou-pvotal, the range in #11 covers any version [greater than or equal to 2.0.0 and less than 4.0.0](https://github.com/google/json_serializable.dart/blob/master/json_serializable/pubspec.yaml#L11).

That range means that users of `xml_serializable` can still use version 2.y.z of `analyzer` without any issues.

Could you upgrade `xml_serializable` to version 2.0.1 and let me know if that solves the dependency conflict?
