### ISSUE TITLE
Include beginner friendly docs

### ISSUE THREAD

**Issue by atn832** [tnc1997/dart-xml-serializable#32]
Unless I mis-read your docs, nowhere does it state step by step how a beginner would use your project. You mention builders without explaining how to run a builder. Maybe you could write something like:
> add build_runner to your dev_dependencies, then run `dart run build_runner build` to generate the files.

In the readme, you show an example piece of code and the resulting generated file. It'd be nice to start by showing the XML you're trying to model.

I think resolving #31 would go a long way to make it beginner friendly.

**Comment by tnc1997** [comment]
Hi @atn832, thank you very much for your issue. I agree that the usage documentation can appear daunting at first. This is something that I will aim to rectify over the coming weeks in order to improve the experience for beginners.
