### ISSUE TITLE
feat: Add support for XML base64Binary type

### ISSUE THREAD

**Issue by Matej-Hlatky** [tnc1997/dart-xml-serializable#46]
**Is your feature request related to a problem? Please describe.**

To be able to map XML type ["base64Binary"](https://www.w3.org/TR/xmlschema-2/#base64Binary), to Dart [`Uint8List`](https://docs.flutter.io/flutter/dart-typed_data/Uint8List-class.html) and vice-versa.

**Describe the solution you'd like**
Support "base64Binary" to be mapped to / from `Uint8List`.

**Describe alternatives you've considered**
Working with plain strings and mapping to Dart type when needed.

**Comment by tnc1997** [comment]
Hi @Matej-Hlatky, thank you for your feature request, I will investigate it over the weekend. In the meantime, I do have a question for you, how might you see [`base64Binary`](https://www.w3.org/TR/xmlschema-2/#base64Binary) interacting with [`hexBinary`](https://www.w3.org/TR/xmlschema-2/#hexBinary) given that both could map to `Uint8List`?

**Comment by Matej-Hlatky** [comment]
Hi Thomas.

I must admit that I didn't knew about hexBinary type. 😅
So it does not make sense to implement support (only) for base64String,
since it wouldn't be unambiguous, when serializing.

Maybe it would require additional param "dataType" in XmlAttribute /
XmlElement annotation, like .NET does it?

Or even better, support for custom XmlConverter (similar to JsonConverter
from json_serializable) would be better best solution.

Thanks a lot.

**Comment by tnc1997** [comment]
> Or even better, support for custom XmlConverter (similar to JsonConverter from json_serializable).

I am in favour of adding support for custom converters similar to the `JsonConverter` class (#49).
