### ISSUE TITLE
Add support for serializing XML CDATA

### ISSUE THREAD

**Issue by tnc1997** [tnc1997/dart-xml-serializable#47]
**Is your feature request related to a problem? Please describe.**
As a developer I would like to serialize and deserialize XML CDATA in addition to XML text.

**Describe the solution you'd like**
I would like the `xml_annotation` package to export an `XmlCDATA` annotation.

**Additional context**
#45

**Comment by tnc1997** [comment]
Hi @mevljas, apologies for the delay in adding support for `XmlCDATA`, could I get you to [test](https://dart.dev/tools/pub/dependencies#git-packages) the branch [`feat/47`](https://github.com/tnc1997/dart-xml-serializable/tree/feat/47)?

**Comment by mevljas** [comment]
Hi! I had no idea you were working on this. I tested it using my example XML and unit tests. It works as expected.
Thanks! :)
