### ISSUE TITLE
Upgrade the version constraint of analyzer

### ISSUE THREAD

**Issue by KristijanZic** [tnc1997/dart-xml-serializable#50]
The current version of analyzer used in xml_serializable is creating issues with various other packages like custom_lint, riverpod_lint, riverpod_generator etc. Please update the library to the latest version to resolve the conflicts.

**Comment by tnc1997** [comment]
Hi @KristijanZic, thanks for opening this issue, I will look to adjust the version constraint of the `analyzer` dependency.
