### ISSUE TITLE
Add support for serializing elements using InnerXml

### ISSUE THREAD

**Issue by justkawal** [tnc1997/dart-xml-serializable#52]
If I use the XML like:
```
<?xml version="1.0"?>
    <bookshelf>
      <book>
        <title lang="English"><RandomUnknownTag>XML Pocket Reference</RandomUnknownTag ></title>
        <author>Simon St. Laurent</author>
        <author>Michael James Fitzgerald</author>
        <price></price>
      </book>
      <book>
        <title lang="English">HTML and XHTML Pocket Reference</title>
        <author>Jennifer Niederst Robbins</author>
        <price></price>
      </book>
    </bookshelf>
 ```
 
 Will it be possible to have an @ InnerXml() `tag` in future request.
 
 which will help to set the value of of text in title class to `<RandomUnknownTag>XML Pocket Reference</RandomUnknownTag>` as an innerXml String.
 
 and back to `<RandomUnknownTag>XML Pocket Reference</RandomUnknownTag>` when generating XML.
 
 
 
 If it is already possible and I'm missing this, Please do let me know how could I achieve this.

**Comment by justkawal** [comment]
Thank you so much for this awesome library.

**Comment by tnc1997** [comment]
Hi @justkawal, thank you very much for your positive feedback!

This functionality might be able to be covered by the ongoing work in https://github.com/tnc1997/dart-xml-serializable/issues/49#issuecomment-1751969686.

In theory implementing the first/third proposal in that comment would allow custom serialization using nested elements.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<example>
    <a>
        <year>2023</year>
        <month>10</month>
        <day>8</day>
    </a>
</example>
```

```dart
@annotation.XmlSerializable()
class Example {
  @annotation.XmlElement()
  @_CustomDateTimeConverter()
  final DateTime a;

  ...
}

class _CustomDateTimeConverter implements annotation.XmlElementConverter<DateTime> {
  const _CustomDateTimeConverter();

  @override
  DateTime fromXmlElement(XmlElement element) => DateTime(
    int.parse(element.getElement('year')!.getText()!),
    int.parse(element.getElement('month')!.getText()!),
    int.parse(element.getElement('day')!.getText()!),
  );

  @override
  XmlElement toXmlElement(DateTime object) => XmlElement(
    XmlName('???'),
    [],
    [
      XmlElement(XmlName('year'), [], [XmlText(object.year.toString())]),
      XmlElement(XmlName('month'), [], [XmlText(object.month.toString())]),
      XmlElement(XmlName('day'), [], [XmlText(object.day.toString())]),
    ],
  );
}
```

Out of interest what might the type look like for the title element in your example?

Would it be typed as a string or a class with a nullable random unknown tag field?

**Comment by justkawal** [comment]
I would be waiting for that feature....
It would be very useful for me....

Any rough expected Idea by when we could have that ready?

**Comment by tnc1997** [comment]
Hi @justkawal, could I get you to [test](https://dart.dev/tools/pub/dependencies#git-packages) the branch [`feat/49`](https://github.com/tnc1997/dart-xml-serializable/tree/feat/49), as I think that an `XmlConverter` could resolve this issue?

**Comment by justkawal** [comment]
> Hi @justkawal, could I get you to [test](https://dart.dev/tools/pub/dependencies#git-packages) the branch [`feat/49`](https://github.com/tnc1997/dart-xml-serializable/tree/feat/49), as I think that an `XmlConverter` could resolve this issue?

I'm humbly sorry for the delay in response. Thomas

**Comment by justkawal** [comment]
Hey I tried it like this:

## On Title class:
```dart

@annotation.XmlRootElement(name: 'title')
@annotation.XmlSerializable()
class Title {
  @annotation.XmlAttribute(name: 'lang')
  String? language;

  @InnerXmlConverter() // changed this line
  @annotation.XmlElement() // changed this line
  String? text;

  Title({
    this.language,
    this.text,
  });

  factory Title.fromXmlElement(XmlElement element) =>
      _$TitleFromXmlElement(element);

  @override
  String toString() {
    return 'Title{language: $language, text: $text}';
  }

  void buildXmlChildren(
    XmlBuilder builder, {
    Map<String, String> namespaces = const {},
  }) =>
      _$TitleBuildXmlChildren(
        this,
        builder,
        namespaces: namespaces,
      );

  void buildXmlElement(
    XmlBuilder builder, {
    Map<String, String> namespaces = const {},
  }) =>
      _$TitleBuildXmlElement(
        this,
        builder,
        namespaces: namespaces,
      );
....
....
....
.... rest of the code same as example from xml_annotation.
```

## Converter

```dart
import 'package:xml/xml.dart';
import 'package:xml_annotation/xml_annotation.dart' as annotation;

class InnerXmlConverter implements annotation.XmlConverter<String> {
  const InnerXmlConverter();

  @override
  void buildXmlChildren(
    String instance,
    XmlBuilder builder, {
    Map<String, String> namespaces = const {},
  }) {
    builder.xml(instance);
  }

  @override
  String fromXmlElement(
    XmlElement? element,
  ) {
    return element?.innerXml ?? '';
  }

  @override
  List<XmlAttribute> toXmlAttributes(
    String instance, {
    Map<String, String?> namespaces = const {},
  }) {
    return <XmlAttribute>[];
  }

  @override
  List<XmlNode> toXmlChildren(
    String instance, {
    Map<String, String?> namespaces = const {},
  }) {
    return <XmlNode>[XmlText(instance)];
  }
}
```

**Comment by justkawal** [comment]
So for clarification simplicity, I just want to set and unset the xml inside the title tag to a variable and thats it, nothing more.

I'm thinking the child tags inside <Title> would be any random tag and I don't want to see what it is and just want to set or unset their `xml` with using `innerXml` getter from the xml library, on the element object.

```
<?xml version="1.0"?>
    <bookshelf>
      <book>
        <title lang="English"><AustraliaTag>XML Pocket Reference</AustraliaTag></title>
        <author>Simon St. Laurent</author>
        <author>Michael James Fitzgerald</author>
        <price></price>
      </book>
        <title lang="English"><EuropeTag>XML Pocket Reference</EuropeTag></title>
        <author>Simon St. Laurent</author>
        <author>Michael James Fitzgerald</author>
        <price></price>
      </book>
      <book>
        <title lang="English">HTML and XHTML Pocket Reference</title>
        <author>Jennifer Niederst Robbins</author>
        <price></price>
      </book>
    </bookshelf>
    <library>
      <room>
        <roomnumber><JapanTag>XML Pocket Reference</JapanTag></roomnumber>
      </room>
      <room>
        <roomnumber><AsiaTag >XML Pocket Reference</AsiaTag></roomnumber>
      </room>
      <room>
        <roomnumber><UnknownRandomInnerXml>XML Pocket Reference</UnknownRandomInnerXml></roomnumber>
      </room>
    </library >
 ```
 
 I just want to set `<JapanTag>XML Pocket Reference</JapanTag>` to the variable and then unset it as the other value would be `<AsiaTag >XML Pocket Reference</AsiaTag>` and I tried using XmlText but it tries to get element.getText() which returns null because it is a element which is random in nature.
 
 
 So, I know for the title class I can make a Title specific converter and easily do it, but what if I had to do it for the other classes too to set and unset innerXml ?
 
 I would duplicating the same piece of code for each and every class but just renaming the variable.
