### ISSUE TITLE
How to Write XML Element Names That Have a $ Sign

### ISSUE THREAD

**Issue by tegarnugroho** [tnc1997/dart-xml-serializable#59]
**Describe the bug**

Hello, I’m encountering an issue while working with XML data. The element names in my XML data contain a $ sign, such as "wsdl$definitions". This causes an error because it is interpreted as a variable.

![Screenshot 2024-08-26 at 14 38 42](https://github.com/user-attachments/assets/e2986740-9a17-4170-b7b9-d926eae649e5)

When I use wsdl\\$definitions to escape the $ sign, it works fine. However, in the automatically generated files, the element name still appears as "wsdl$definitions", which causes errors when the application is run.

![Screenshot 2024-08-26 at 14 56 47](https://github.com/user-attachments/assets/7d8e7cd6-99fd-4c25-90d7-84cf14f6926b)

Do you have a solution for this issue? How can I ensure that the element names in the generated files match the desired format and avoid errors when the application is run?

**Comment by tnc1997** [comment]
Hi @tegarnugroho, thanks for reporting this issue, I will investigate further and let you know.

**Comment by tnc1997** [comment]
Hi @tegarnugroho, could I get you to verify that the changes in [this](https://github.com/tnc1997/dart-xml-serializable/tree/fix/59) branch resolve this issue for you?

**Comment by tegarnugroho** [comment]
Okay, I will get back to you with the results.

**Comment by tegarnugroho** [comment]
Yes, the changes in [this](https://github.com/tnc1997/dart-xml-serializable/tree/fix/59) branch have resolved the issue. Everything looks great now. Thank you for addressing this!

**Comment by tegarnugroho** [comment]
Yes, the changes in [this](https://github.com/tnc1997/dart-xml-serializable/tree/fix/59) branch have resolved the issue. Everything looks great now. Thank you
