### ISSUE TITLE
Converter for repeated elements generates wrong code

### ISSUE THREAD

**Issue by Rossi1337** [tnc1997/dart-xml-serializable#63]
This is related to Issue #54

To properly parse empty strings into my model classes I apply a Converter via annotation to my classes.

The converter should handle "String" and make sure that we do not assign null to a String member field.

Here my converter:

```
class StringEmptyConverter extends an.XmlConverter<String> {
  const StringEmptyConverter();

  @override
  void buildXmlChildren(
    String instance,
    XmlBuilder builder, {
    Map<String, String> namespaces = const {},
  }) {
    builder.text(instance);
  }

  @override
  String fromXmlElement(XmlElement element) {
    return element.getText() ?? '';
  }

  @override
  List<XmlAttribute> toXmlAttributes(
    String instance, {
    Map<String, String?> namespaces = const {},
  }) {
    return List.empty();
  }

  @override
  List<XmlNode> toXmlChildren(
    String instance, {
    Map<String, String?> namespaces = const {},
  }) {
    return [XmlText(instance)];
  }
}
```

Now I have a model class that has some String members and for these everything works fine. But I also have List<String> and for these the converter fails. The generated code is invalid.

Here an example of my model class:

```
@annotation.XmlRootElement(name: 'stackTrace')
@annotation.XmlSerializable()
@StringEmptyConverter()
class StackTraceModel {
  @annotation.XmlElement(name: 'description')
  String description;

  @annotation.XmlElement(name: 'message')
  String message;

  @annotation.XmlElement(name: 'stack')
  List<String> stack;

  StackTraceModel({
    required this.description,
    required this.message,
    required this.stack,
  });
...
```

The problem is with the  List<String> stack; field.

The generated code looks like this.

```
StackTraceModel _$StackTraceModelFromXmlElement(XmlElement element) {
  final description = element.getElement('description')!;
  final message = element.getElement('message')!;
  final stack =
      element.getElements('stack')!.map((e) => e.getText()).whereType<String>();
  return StackTraceModel(
      description: const StringEmptyConverter().fromXmlElement(description),
      message: const StringEmptyConverter().fromXmlElement(message),
      stack: stack
          .map((e) => const StringEmptyConverter().fromXmlElement(e))
          .toList());
}
```

Here the problem is that stack is parsed to a list of "String" but then later it is "mapped" with the converter. There e is of type String.

```
 .map((e) => const StringEmptyConverter().fromXmlElement(e))
```

This fails because fromXmlElement(e) does not expect "String" but "XmlElement"

The code would work if I replace 

```
final stack =
      element.getElements('stack')!.map((e) => e.getText()).whereType<String>();
```
with 
```
final stack = element.getElements('stack')!;
```

So when a converter is set on a field the mapping should be skipped in the first place.

**Comment by tnc1997** [comment]
Hi @Rossi1337, thank you very much for using this package and opening this issue.

I will aim to investigate this issue further this week and get a bug fix released.

**Comment by Rossi1337** [comment]
Seems to happen here: https://github.com/tnc1997/dart-xml-serializable/blob/2630ea2f937b18bdcb6a6deb356bad03bb06f190/xml_serializable/lib/src/getter_generators/xml_text_xml_element_iterable_getter_generator.dart#L20

Thanks for taking care.
